#!/usr/bin/env python3

import click

from main import app
from core.app import CliApp
from cli import register_cli_commands


@click.group()
@click.pass_context
def cli(ctx):
    """CLI for the Server"""
    ctx.obj = CliApp(app)


register_cli_commands(cli)


if __name__ == '__main__':
    cli()
