"""empty message

Revision ID: ffd3911dd341
Revises: 91c069296571
Create Date: 2025-07-29 01:05:59.444958

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import context, op
from edgy import monkay, run_sync


# revision identifiers, used by Alembic.
revision = 'ffd3911dd341'
down_revision = '91c069296571'
branch_labels = None
depends_on = None


def hash_to_identifier(key: str | bytes) -> str:
    from base64 import b32encode
    from hashlib import blake2b
    if isinstance(key, str):
        key = key.encode()
    return f"_{b32encode(blake2b(key, digest_size=16).digest()).decode().rstrip('=')}"

force_fields_nullable: list[tuple[str, str]] = []

def upgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"upgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()


def downgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"downgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()




def upgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_job_job_status_status', 'job_status', ['status'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key('fk_job_job_categories_category', 'job_categories', ['category'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###
    if not context.is_offline_mode():
        try:
            with monkay.instance.registry.with_async_env():
                run_sync(
                    monkay.instance.registry.apply_default_force_nullable_fields(
                        force_fields_nullable=force_fields_nullable,
                        filter_db_name="",
                        model_defaults={}
                    )
                )
        except Exception as exc:
            print("failure migrating defaults", exc)


def downgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('fk_job_job_categories_category', type_='foreignkey')
        batch_op.drop_constraint('fk_job_job_status_status', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('category')

    # ### end Alembic commands ###

