"""empty message

Revision ID: b89f4d7bbf5c
Revises: 333bcb0b9f60
Create Date: 2025-07-31 09:00:57.124247

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import context, op
from edgy import monkay, run_sync


# revision identifiers, used by Alembic.
revision = 'b89f4d7bbf5c'
down_revision = '333bcb0b9f60'
branch_labels = None
depends_on = None


def hash_to_identifier(key: str | bytes) -> str:
    from base64 import b32encode
    from hashlib import blake2b
    if isinstance(key, str):
        key = key.encode()
    return f"_{b32encode(blake2b(key, digest_size=16).digest()).decode().rstrip('=')}"

force_fields_nullable: list[tuple[str, str]] = []

def upgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"upgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()


def downgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"downgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()




def upgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_reports',
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.String(length=1000), autoincrement=False, nullable=False),
    sa.Column('include_diagnostics', sa.Boolean(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('include_tasks', sa.Boolean(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('job', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('customer_signature', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('operator_signature', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.Integer(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_job_reports_users_created_by', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job'], ['job.id'], name='fk_job_reports_job_job', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace'], ['workspaces.id'], name='fk_job_reports_workspaces_workspace', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    if not context.is_offline_mode():
        try:
            with monkay.instance.registry.with_async_env():
                run_sync(
                    monkay.instance.registry.apply_default_force_nullable_fields(
                        force_fields_nullable=force_fields_nullable,
                        filter_db_name="",
                        model_defaults={}
                    )
                )
        except Exception as exc:
            print("failure migrating defaults", exc)


def downgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_reports')
    # ### end Alembic commands ###

