"""Add Company model

Revision ID: b81b888b584b
Revises: ce4cd013cdc1
Create Date: 2025-07-28 12:01:25.753690

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import context, op
from edgy import monkay, run_sync


# revision identifiers, used by Alembic.
revision = 'b81b888b584b'
down_revision = 'ce4cd013cdc1'
branch_labels = None
depends_on = None


def hash_to_identifier(key: str | bytes) -> str:
    from base64 import b32encode
    from hashlib import blake2b
    if isinstance(key, str):
        key = key.encode()
    return f"_{b32encode(blake2b(key, digest_size=16).digest()).decode().rstrip('=')}"

force_fields_nullable: list[tuple[str, str]] = []

def upgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"upgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()


def downgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"downgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()




def upgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('reference', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('company_type', sa.Enum('CLIENT_FINAL', 'REGIE_GESTIONNAIRE', 'DONNEUR_ORDRE', 'SOUS_TRAITANT', 'FOURNISSEUR', 'AUTRE', name='companytype'), server_default=sa.text("'CLIENT_FINAL'"), autoincrement=False, nullable=False),
    sa.Column('phone', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('invoice_street', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('invoice_zip', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('invoice_city', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('invoice_country', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('siret', sa.String(length=14), autoincrement=False, nullable=True),
    sa.Column('vat', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_country'], ['countries.id'], name='fk_companies_countries_invoice_country', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    if not context.is_offline_mode():
        try:
            with monkay.instance.registry.with_async_env():
                run_sync(
                    monkay.instance.registry.apply_default_force_nullable_fields(
                        force_fields_nullable=force_fields_nullable,
                        filter_db_name="",
                        model_defaults={}
                    )
                )
        except Exception as exc:
            print("failure migrating defaults", exc)


def downgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###

