"""add job attachment model

Revision ID: 780cffe4e825
Revises: b89f4d7bbf5c
Create Date: 2025-07-31 17:49:59.755136

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import context, op
from edgy import monkay, run_sync


# revision identifiers, used by Alembic.
revision = '780cffe4e825'
down_revision = 'b89f4d7bbf5c'
branch_labels = None
depends_on = None


def hash_to_identifier(key: str | bytes) -> str:
    from base64 import b32encode
    from hashlib import blake2b
    if isinstance(key, str):
        key = key.encode()
    return f"_{b32encode(blake2b(key, digest_size=16).digest()).decode().rstrip('=')}"

force_fields_nullable: list[tuple[str, str]] = []

def upgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"upgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()


def downgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"downgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()




def upgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_attachments',
    sa.Column('job', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('job_activity', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.String(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('file_extension', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('is_image', sa.Boolean(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_job_attachments_users_created_by', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job'], ['job.id'], name='fk_job_attachments_job_job', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_activity'], ['job_activities.id'], name='fk_job_attachments_job_activities_job_activity', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_job_attachments_users_updated_by', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace'], ['workspaces.id'], name='fk_job_attachments_workspaces_workspace', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.replace_enum('jobactivitytype', ['message', 'note', 'tracking_create', 'tracking_update', 'attachments'], ['message', 'note', 'tracking_create', 'tracking_update'])
    # ### end Alembic commands ###
    if not context.is_offline_mode():
        try:
            with monkay.instance.registry.with_async_env():
                run_sync(
                    monkay.instance.registry.apply_default_force_nullable_fields(
                        force_fields_nullable=force_fields_nullable,
                        filter_db_name="",
                        model_defaults={}
                    )
                )
        except Exception as exc:
            print("failure migrating defaults", exc)


def downgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.replace_enum('jobactivitytype', ['message', 'note', 'tracking_create', 'tracking_update'], ['message', 'note', 'tracking_create', 'tracking_update', 'attachments'])
    op.drop_table('job_attachments')
    # ### end Alembic commands ###

