"""update job activity model

Revision ID: 333bcb0b9f60
Revises: ed1d74c61e17
Create Date: 2025-07-30 18:09:06.401664

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import context, op
from edgy import monkay, run_sync


# revision identifiers, used by Alembic.
revision = '333bcb0b9f60'
down_revision = 'ed1d74c61e17'
branch_labels = None
depends_on = None


def hash_to_identifier(key: str | bytes) -> str:
    from base64 import b32encode
    from hashlib import blake2b
    if isinstance(key, str):
        key = key.encode()
    return f"_{b32encode(blake2b(key, digest_size=16).digest()).decode().rstrip('=')}"

force_fields_nullable: list[tuple[str, str]] = []

def upgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"upgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()


def downgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"downgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()




def upgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.replace_enum('jobactivitytype', ['message', 'note', 'tracking_create', 'tracking_update'], ['MESSAGE', 'NOTE', 'TRACKING_CREATE', 'TRACKING_UPDATE'])
    op.replace_enum('jobactivityvaluetype', ['string', 'integer', 'float', 'bool', 'object'], ['STRING', 'INTEGER', 'FLOAT', 'BOOL', 'OBJECT'])
    # ### end Alembic commands ###
    if not context.is_offline_mode():
        try:
            with monkay.instance.registry.with_async_env():
                run_sync(
                    monkay.instance.registry.apply_default_force_nullable_fields(
                        force_fields_nullable=force_fields_nullable,
                        filter_db_name="",
                        model_defaults={}
                    )
                )
        except Exception as exc:
            print("failure migrating defaults", exc)


def downgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.replace_enum('jobactivityvaluetype', ['STRING', 'INTEGER', 'FLOAT', 'BOOL', 'OBJECT'], ['string', 'integer', 'float', 'bool', 'object'])
    op.replace_enum('jobactivitytype', ['MESSAGE', 'NOTE', 'TRACKING_CREATE', 'TRACKING_UPDATE'], ['message', 'note', 'tracking_create', 'tracking_update'])
    # ### end Alembic commands ###

