"""empty message

Revision ID: e2fbbedfefe1
Revises: 810e18f857ec
Create Date: 2025-07-28 10:22:10.077495

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import context, op
from edgy import monkay, run_sync


# revision identifiers, used by Alembic.
revision = 'e2fbbedfefe1'
down_revision = '810e18f857ec'
branch_labels = None
depends_on = None


def hash_to_identifier(key: str | bytes) -> str:
    from base64 import b32encode
    from hashlib import blake2b
    if isinstance(key, str):
        key = key.encode()
    return f"_{b32encode(blake2b(key, digest_size=16).digest()).decode().rstrip('=')}"

force_fields_nullable: list[tuple[str, str]] = []

def upgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"upgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()


def downgrade(engine_name: str = "") -> None:
    # hash_to_identifier adds already an "_"
    fn = globals().get(f"downgrade{hash_to_identifier(engine_name)}")
    if fn is not None:
        fn()




def upgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_enum('defaultjobduration', ['minutes_60', 'minutes_90', 'minutes_120', 'minutes_180', 'minutes_240', 'minutes_300', 'minutes_360', 'minutes_420', 'minutes_480'])
    op.create_enum('defaultjobpriority', ['low', 'normal', 'high', 'urgent'])
    
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_job_duration', sa.Enum('minutes_90', 'minutes_120', 'minutes_180', 'minutes_240', 'minutes_300', 'minutes_360', 'minutes_420', 'minutes_480', name='defaultjobduration'), server_default=sa.text("'minutes_60'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('default_job_priority', sa.Enum('low', 'normal', 'high', 'urgent', name='defaultjobpriority'), server_default=sa.text("'normal'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('metadata', sa.JSON(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
    if not context.is_offline_mode():
        try:
            with monkay.instance.registry.with_async_env():
                run_sync(
                    monkay.instance.registry.apply_default_force_nullable_fields(
                        force_fields_nullable=force_fields_nullable,
                        filter_db_name="",
                        model_defaults={}
                    )
                )
        except Exception as exc:
            print("failure migrating defaults", exc)


def downgrade_ZLTGSQOZ566UATSNRB2Y5JTWOA():
    # Migration of:
    # main database
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('metadata')
        batch_op.drop_column('default_job_priority')
        batch_op.drop_column('default_job_duration')
    
    op.drop_enum('defaultjobpriority', ['low', 'normal', 'high', 'urgent'])
    op.drop_enum('defaultjobduration', ['minutes_60', 'minutes_90', 'minutes_120', 'minutes_180', 'minutes_240', 'minutes_300', 'minutes_360', 'minutes_420', 'minutes_480'])

    # ### end Alembic commands ###

